version: '3.7'

services:
  spark-master:
    build: .
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./:/app/
       # - ./spark-conf/spark-defaults.conf:/opt/bitnami/spark/conf/
    environment:
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      SPARK_PUBLIC_DNS: localhost
      # SPARK_LOCAL_IP: spark-master
      # SPARK_MASTER_HOST:
      # SPARK_LOG_DIR: /opt/spark/logs
      # SPARK_MASTER_LOG: /opt/spark/logs/spark-master.out
      # SPARK_WORKER_LOG: /opt/spark/logs/spark-worker.out
  spark-worker-1:
    build: .
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "9091:8080"
      - "7000:7000"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 6g
      # SPARK_DRIVER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 8080
      SPARK_PUBLIC_DNS: localhost
      # SPARK_WORKER_PORT: 7000
    volumes:
       - ./:/app/
       - ./spark-conf/:/opt/bitnami/spark/conf/
  spark-worker-2:
    build: .
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "9092:8080"
      - "7001:7000"
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 6g
      # SPARK_DRIVER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 8080
      SPARK_PUBLIC_DNS: localhost
      # SPARK_WORKER_PORT: 7000
    volumes:
       - ./:/app/
       - ./spark-conf/:/opt/bitnami/spark/conf/
  # spark-worker-3:
  #   build: .
  #   command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "9093:8080"
  #     - "7002:7000"
  #   environment:
  #     SPARK_MODE: worker
  #     SPARK_WORKER_CORES: 2
  #     SPARK_WORKER_MEMORY: 5g
  #     # SPARK_DRIVER_MEMORY: 2g
  #     SPARK_MASTER_URL: spark://spark-master:7077
  #     SPARK_WORKER_WEBUI_PORT: 8080
  #     SPARK_PUBLIC_DNS: localhost
  #     # SPARK_WORKER_PORT: 7000
  #   volumes:
  #      - ./:/app/
  #      - ./spark-conf/:/opt/bitnami/spark/conf/
  # spark-worker-4:
  #   build: .
  #   command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  #   depends_on:
  #     - spark-master
  #   ports:
  #     - "9094:8080"
  #     - "7003:7000"
  #   environment:
  #     SPARK_MODE: worker
  #     SPARK_WORKER_CORES: 2
  #     SPARK_WORKER_MEMORY: 5g
  #     # SPARK_DRIVER_MEMORY: 2g
  #     SPARK_MASTER_URL: spark://spark-master:7077
  #     SPARK_WORKER_WEBUI_PORT: 8080
  #     SPARK_PUBLIC_DNS: localhost
  #     # SPARK_WORKER_PORT: 7000
  #   volumes:
  #      - ./:/app/
  #      - ./spark-conf/:/opt/bitnami/spark/conf/
